name: CI
on: [push,pull_request]
jobs:
  lint:
    name: Golangci-lint
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Intsall Golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b . v1.34.1
      - name: Lint
        run: ./golangci-lint run --fix

  test:
    name: Unit Testing
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Checkout
        uses: actions/checkout@v2
      - name: Go Test
        run: go test -v ./...
